name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule: 
    - cron: 30 02 * * * #8:00 AM IST
    - cron: 00 14 * * * #7:30 PM IST

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v6.0.0

      - name: install node js and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'

      - name: install newman and newman htmlextra
        run: |
              npm install -g newman 
              npm install -g newman-reporter-htmlextra
    
      - name: Run the postman collection with newman
        run: |
              newman run 'Pheonix-Inwarranty-Flow Collection.postman_collection.json' \
              -e QA.postman_environment.json \
              -d testData.csv \
              -r cli,htmlextra

      - name: Newman Report
        if: always() #ensure archive section gets exucuted even if we have failure tests
        uses: actions/upload-artifact@v5.0.0
        with:
          name: Newman Report
          path: newman/*.html
    
  
